export const units = [
  {
    id: "recife-antigo",
    name: "Recife Antigo",
    city: "Recife, PE",
    channel: "App, balcão e retirada",
    hours: "10h às 22h",
    rules: "Retirada em até 25 minutos. Cardápio com pratos executivos no almoço.",
    features: ["Mais pedidos no app", "Pratos executivos", "Pix e cartão via parceiro"],
    imageUrl: "https://images.pexels.com/photos/28759063/pexels-photo-28759063.jpeg",
  },
  {
    id: "natal-ponta-negra",
    name: "Natal Ponta Negra",
    city: "Natal, RN",
    channel: "Totem, app e balcão",
    hours: "11h às 23h",
    rules: "Produtos sazonais de praia aparecem apenas nesta unidade.",
    features: ["Autoatendimento", "Itens sazonais", "Retirada prioritária"],
    imageUrl: "https://images.pexels.com/photos/15790865/pexels-photo-15790865.jpeg",
  },
  {
    id: "salvador-rio-vermelho",
    name: "Salvador Rio Vermelho",
    city: "Salvador, BA",
    channel: "App e pedidos para retirada",
    hours: "12h às 23h",
    rules: "Pedidos acima de R$ 80 recebem pontos extras no programa de fidelidade.",
    features: ["Fidelidade ativa", "Cardápio regional", "Alta demanda noturna"],
    imageUrl: "https://images.pexels.com/photos/16949681/pexels-photo-16949681.jpeg",
  },
];

export const products = [
  {
    id: "baiao-da-casa",
    name: "Baião da Casa",
    category: "Pratos",
    price: 34.9,
    seasonal: false,
    availableIn: ["recife-antigo", "natal-ponta-negra", "salvador-rio-vermelho"],
    imageUrl: "https://images.pexels.com/photos/19781591/pexels-photo-19781591.jpeg",
    description:
      "Arroz, feijão verde, queijo coalho e carne de sol em uma porção individual.",
    tags: ["Sem dados pessoais", "Mais vendido"],
    prepTime: "18 min",
  },
  {
    id: "tapioca-sertao",
    name: "Tapioca Sertão",
    category: "Lanches",
    price: 18.5,
    seasonal: false,
    availableIn: ["recife-antigo", "natal-ponta-negra"],
    imageUrl: "https://images.pexels.com/photos/11094180/pexels-photo-11094180.jpeg",
    description: "Tapioca recheada com queijo coalho, tomate carne seca vegetal e ervas.",
    tags: ["Vegetariano", "Retirada rápida"],
    prepTime: "10 min",
  },
  {
    id: "moqueca-raizes",
    name: "Moqueca Raízes",
    category: "Pratos",
    price: 46.9,
    seasonal: false,
    availableIn: ["salvador-rio-vermelho"],
    imageUrl: "https://images.pexels.com/photos/3493579/pexels-photo-3493579.jpeg",
    description: "Moqueca individual com arroz, farofa e pirão.",
    tags: ["Unidade Salvador", "Pedido especial"],
    prepTime: "25 min",
  },
  {
    id: "suco-caju",
    name: "Suco de Caju",
    category: "Bebidas",
    price: 9.9,
    seasonal: true,
    availableIn: ["natal-ponta-negra", "recife-antigo"],
    imageUrl: "https://images.pexels.com/photos/12448626/pexels-photo-12448626.jpeg",
    description: "Bebida sazonal, sujeita a disponibilidade local.",
    tags: ["Sazonal", "Gelado"],
    prepTime: "4 min",
  },
  {
    id: "cafe-rapadura",
    name: "Café com Rapadura",
    category: "Bebidas",
    price: 7.5,
    seasonal: false,
    availableIn: ["recife-antigo", "salvador-rio-vermelho"],
    imageUrl: "https://images.pexels.com/photos/34567220/pexels-photo-34567220.jpeg",
    description: "Café coado com toque de rapadura, servido quente.",
    tags: ["Quente", "Tradicional"],
    prepTime: "6 min",
  },
  {
    id: "bolo-rolo",
    name: "Bolo de Rolo",
    category: "Sobremesas",
    price: 13.9,
    seasonal: false,
    availableIn: ["recife-antigo"],
    imageUrl: "https://images.pexels.com/photos/7509689/pexels-photo-7509689.jpeg",
    description: "Fatia de bolo de rolo com goiabada cremosa.",
    tags: ["Unidade Recife", "Sobremesa"],
    prepTime: "5 min",
  },
];

export const orderSteps = ["Recebido", "Em preparo", "Pronto para retirada", "Finalizado"];
